spring.datasource.url=jdbc:postgresql://localhost:5432/clinica_ucsal
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# chave usada para assinar e verificar os tokens JWT (mínimo 32 caracteres)
jwt.secret=ucsal-clinica-medica-secret-key-2026-super-muito-segura-1234567890

# tempo de expiração do token em milissegundos (7 dias = 604800000)
jwt.expiration=604800000
